language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - yarn
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
  - bundle exec rails db:migrate
script:
  - bundle exec rspec